name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file FeatureDocCLI/pom.xml -DskipTests

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cli-jar
        path: FeatureDocCLI/target/*.jar

